# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PivotLang < Formula
  desc "Https://langpivotstudiocn"
  homepage "https://github.com/Pivot-Studio/pivot-lang"
  url "https://github.com/Pivot-Studio/pivot-lang/archive/v0.1.344.tar.gz"
  sha256 "2b02e4fab0d6cd278f2946a68422db11fefd4293bc5549f5d8e8af9d19c3d4bb"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Pivot-Studio/pivot-lang/releases/download/v0.1.344/pivot-lang-0.1.344-darwin-amd64.tar.gz"
      sha256 "181086a5a53d19e8a2379e24fbf99e63b82fb95f93e36c8f3dc175b0228d9752"
    end

    on_arm do
      url "https://github.com/Pivot-Studio/pivot-lang/releases/download/v0.1.344/pivot-lang-0.1.344-darwin-arm64.tar.gz"
      sha256 "0ffe4de0cacab2241c0e0ccf9a8a835a805bf043d93ebdcd230bd1cf7e3fd4b1"
    end
  end

  def install
    lib.install Dir["./planglib"]
    lib.install "./libvm.a"
    bin.install "./plc"
  end

  def caveats
    s = <<~EOS
    [0;32m安装完成，请运行下方命令添加环境变量[0m
      echo 'export KAGARI_LIB_ROOT=$(brew --prefix pivot-lang)/lib/planglib' >> ~/.bash_profile
      echo 'export PL_ROOT=$(brew --prefix pivot-lang)/lib' >> ~/.bash_profile
      source ~/.bash_profile
    [0;32m如果您已经打开了vsc，可能需要重启它来应用环境变量更改[0m
    EOS
    s
  end
end
